version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-sila
    environment:
      POSTGRES_DB: "prod_db"
      POSTGRES_USER: "prod_user"
      POSTGRES_PASSWORD: "prod_pass"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      dockerfile: deploy/Dockerfile
    environment:
      POSTGRES: postgresql://prod_user:prod_pass@postgres:5432/prod_db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres: